### ISSUE TITLE
【需求】这个 cluster 库可以支持其他框架吗？看到有个 framework options

### ISSUE THREAD

**Issue by biaomingzhong** [eggjs/egg-cluster#114]
团队有项目使用了 nest.js 或 fastify，这个库可以适配这种使用场景吗？

- PS: pm2 不考虑因为 license 问题

**Comment by biaomingzhong** [comment]
或者麻烦大佬给一些思路自行改造也行

**Comment by killagu** [comment]
主要的逻辑在 https://github.com/eggjs/egg-cluster/blob/master/lib/master.js 这里。其他的框架没有 agent 这种架构，forkAgent 可能需要干掉，主要看 forkAppWorkers 就行。
